version: '3.4'

services:
  orderdb:
    container_name: orderdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  cartdb:
    container_name: cartdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  catalogdb:
    container_name: catalogdb
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin1234!
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin 

  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cartdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - cartdb
      - rabbitmq
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:mongoDb=mongodb://orderdb:27017"
      - MongoDbName=delivery
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - "ConnectionStrings:DefaultConnection=Data Source=catalogdb,1433;Initial Catalog=DeliveryDb;User Id=SA; Password=admin1234!; TrustServerCertificate=True;"
    ports:
      - "8005:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - catalogdb

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=catalogdb,1433;Database=UserDb;User Id=SA;Password=admin1234!;TrustServerCertificate=True;"
      - "JwtIssuer=http://localhost:8007"
      - "JwyAudience=http://localhost:8010"
      - "JwtSecurityKey=random key value for encodingjewfbjhb"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "8007:80"
    depends_on:
      - catalogdb

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:UserApi=http://user.api"
      - "ApiSettings:OrderApi=http://ordering.api"
      - "ApiSettings:CatalogApi=http://catalog.api"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
      - "8008:80"
    depends_on:
      - user.api
      - ordering.api
      - catalog.api

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "JwtAuthority=http://localhost:8007"
      - "JwyAudience=http://localhost:8010"
      - "JwtSecurityKey=random key value for encodingjewfbjhb"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - cart.api
      - discount.api
      - ordering.api
      - catalog.api
      - user.api
      - shopping.aggregator
    ports:
      - "8010:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data   

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 